### ISSUE TITLE
Moto Mods Kernel modules source missing (gb-***.ko files)

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/readme#11]
Hi, 
these days i'm working on Moto z (griffin) kernel, but i don't know where i can find moto mods module sources to compile them on my custom kernel i mean those "gb-***.ko"(like "gb-battery.ko") files on stock firmware's 
are those sources going to be public?

thanks

**Comment by awheeler-mmi** [comment]
Hey Erfan,

Take a look here<https://github.com/MotorolaMobilityLLC/motorola-external-greybus>.

-andrew
________________________________

**Comment by erfanoabdi** [comment]
woohoo, thanks
