### ISSUE TITLE
How to compile "v4l2-hal.ko" ?

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/readme#12]
Hi, 
i built my custom kernel for Moto Z (griffin) and everything looks good i have all modules except "v4l2-hal.ko" i know it's related to Camera Mod (Hasselblad) and "Service 'mods_camd'" but i don't know how to compile this module 
i searched web about "v4l2-hal.c" and nothing founds 
my dmesg without it : 
`init: Service 'mods_camd' (pid 1057) exited with status 0`
`init: Service 'mods_camd' (pid 1057) killing any children in process group`

please help me to compile this 
thanks

**Comment by ccfries** [comment]
let me check, there should be a motorola/external/v4l2_hal

**Comment by erfanoabdi** [comment]
sorry but I can't find it could you please send link 
Thanks

**Comment by ccfries** [comment]
Yeah, sorry we left it out, it was a mistake in how we added the license files in this new git and the tools missed it.  Charles just pushed it up.

-Chris
