### ISSUE TITLE
Boot files programmer_8210.mbn and singleimage_8210.mbn

### ISSUE THREAD

**Issue by JunioCalu** [MotorolaMobilityLLC/readme#15]
Hi,
My device moto E xt1506 is bricked after an OTA update, by researching the XDA forum developers found out that I need the files programmer_8210.mbn and singleimage_8210.mbn to re-use the fastboot. Thanks for the help.

**Comment by SuryaPrakashChinta** [comment]
Hello JunioCalu,
                     This is Surya from India. Is you found programmer_8210.mbn and singleimage_8210.mbn files to solve your problem. If the files is with you then please give me the files to solve my problem too.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
