### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by MandySingh3** [MotorolaMobilityLLC/readme#16]
Where the file located searched google and everywhere but not got it Download vendor-lenovo-sdcardfs repo

https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-XT1663-S0124-161215.txt#L17

**Comment by chenyt9** [comment]
Please fetch the code from：
git@github.com:MotorolaMobilityLLC/vendor-lenovo-sdcardfs.git -b 
tags： MMI-XT1663-S0124-161215
Thanks.

**Comment by MandySingh3** [comment]
thanks fr the link
