### ISSUE TITLE
Build Instruction Moto Z2 Play

### ISSUE THREAD

**Issue by rahulsnair** [MotorolaMobilityLLC/readme#17]
Please confirm Moto Z2 Play XT1610 build instructions, oreo kernel sources already released
@charleseb 
@chenyt9

**Comment by chenyt9** [comment]
Hi, @rahulsnair ,
Please refer to this text:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-OPS27.76-12-25.txt
Thanks.

**Comment by rahulsnair** [comment]
@chenyt9 I believe greybus  is left out.
