### ISSUE TITLE
Moto G6 XT1925

### ISSUE THREAD

**Issue by secuflag** [MotorolaMobilityLLC/readme#18]
Hello,

would be possible to have build instructions for the Moto G6 XT1925 please?

Thanks.

**Comment by charleseb** [comment]
Hi @secuflag,

Could you inform the release version you need, please?

Thanks,
Charles

**Comment by secuflag** [comment]
Hi @charleseb,

on my phone I have build OPS27.82-72 with kernel 3.18.71-perf-g9696d12a

Thanks.

**Comment by Jleeblanch** [comment]
@charleseb If there is any difference in building release OPS27.104-15-10 for Moto G6 (xt1625-6) could you please include those build instructions as well? Thank you.

**Comment by chenyt9** [comment]
@secuflag ,@Jleeblanch ,
Please refer to this file:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-OPS27.104-15-10.txt
Thanks.
