### ISSUE TITLE
Moto G6 play XT1922-7

### ISSUE THREAD

**Issue by madbat99** [MotorolaMobilityLLC/readme#21]
Hello,

Would it be possible to have build instructions for Moto G6 play Jeter XT1922-7?
Build OCPS27.91-150-2

**Comment by madbat99** [comment]
Re posted in correct place

**Comment by vinimed** [comment]
Hello. Due to the time without answers, I will close this issue. If you are still needing the instructions above, please reopen the issue. Thank you.
