### ISSUE TITLE
Issue with MotoG5 Plus build

### ISSUE THREAD

**Issue by nikhilgeo** [MotorolaMobilityLLC/readme#22]
The first build gives error:
`make -j12 -C kernel O=$kernel_out_dir ARCH=arm CROSS_COMPILE=$cross KBUILD_BUILD_USER= KBUILD_BUILD_HOST= defoldconfig`

```
drivers/pinctrl/Kconfig:206: can't open file "drivers/pinctrl/berlin/Kconfig"
make[2]: *** [defoldconfig] Error 1
make[1]: *** [defoldconfig] Error 2
```
In my case the Kconfig already exist and it's 
`lrwxrwxrwx  1 user group 257 Feb 10 01:22 Kconfig -> if ARCH_BERLIN??config PINCTRL_BERLIN??bool??select PINMUX??select REGMAP_MMIO??config PINCTRL_BERLIN_BG2??bool??select PINCTRL_BERLIN??config PINCTRL_BERLIN_BG2CD??bool??select PINCTRL_BERLIN??config PINCTRL_BERLIN_BG2Q??bool??select PINCTRL_BERLIN??endif?`

Any ideas on how to resolve this ?

**Comment by vinimed** [comment]
After a long time without any answer, we are closing the issue. If you are still facing the errors above, please re-open the issue.
Thank you.
