### ISSUE TITLE
PPO - Ocean build guide

### ISSUE THREAD

**Issue by Dark98** [MotorolaMobilityLLC/readme#24]
Could you release this please?
@charleseb @chenyt9

**Comment by Dark98** [comment]
@charleseb ?

**Comment by charleseb** [comment]
Hi @Dark98,

I'll release it soon.

Thanks,
Charles

**Comment by Dark98** [comment]
@charleseb
Hey,
Thank you! Do you know a rough time gap?

**Comment by charleseb** [comment]
Hi @Dark98,

Readme file released:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPO29.80-27.txt

**Comment by Dark98** [comment]
@charleseb 
Thank You!
what version of dtc should be used for compiling? getting different errors with different versions

**Comment by Dark98** [comment]
@charleseb hey?

**Comment by charleseb** [comment]
Hi @Dark98,

You can find the dtc prebuilt binary here:
https://github.com/MotorolaMobilityLLC/readme/tree/master/dtc_MMI-PPO29.80-27
Version: DTC 1.4.2-Android-build
