### ISSUE TITLE
MotoE4Plus Build Instructions Need Help!!!!!!!!!

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/readme#28]
Hi there,
I am following these instruction for building but getting error, I think instructions provided are missing something can anyone help ??????

https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-NMA26.42-82.txt

Regards.

**Comment by vinimed** [comment]
Hello @ghost, Are you still facing the issue above?

**Comment by vinimed** [comment]
After a long time without any answer, we are closing the issue. If you are still facing the errors above, please re-open the issue.
Thank you.
