### ISSUE TITLE
Build instructions for Motorola One (Deen)

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/readme#29]
Can you provide these please, thanks

**Comment by charleseb** [comment]
Hi @electimon,

Could you describe the version you need, please?

Thanks,
Charles

**Comment by electimon** [comment]
This one, QPK30.54-22 thanks

**Comment by electimon** [comment]
Any update? @charleseb

**Comment by charleseb** [comment]
Hi @electimon,

I'm still working to release this readme file.
It will be released tomorrow.

Thanks,
Charles

**Comment by electimon** [comment]
Thank you :)

**Comment by charleseb** [comment]
Hi @electimon,
Sorry about the delay. I forgot the holiday. It will be available on Monday.

-Charles

**Comment by electimon** [comment]
No problem

**Comment by charleseb** [comment]
Hi @electimon,
Readme released:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPK30.54-22.txt

Thanks,
Charles
