### ISSUE TITLE
Request for Moto G6 Play Build Instructions

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/readme#31]
@charleseb Hey can you provide the readme for Moto G6 Play?
Aljeter PPPS29.55-25-2
Jeter PCP29.118-41
Thanks alot

**Comment by charleseb** [comment]
Readme files released:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPPS29.55-25-2.txt
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PCP29.118-41.txt
