### ISSUE TITLE
Android 10 build instructions for Ocean

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/readme#32]
Hi! Can we get the build instructions for kernel tag, MMI-QPOS30.52-29-2? Thanks

**Comment by electimon** [comment]
@awheeler-mmi ping

**Comment by chenyt9** [comment]
@electimon ,Pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPOS30.52-29-2
