### ISSUE TITLE
Android 9 build instructions for Moto e6 (surfna)

### ISSUE THREAD

**Issue by klabit87** [MotorolaMobilityLLC/readme#33]
I formally request build instructions for surfna on firmware version MMI-PPB29.73-81
Thank you for your time.

**Comment by wh0dat** [comment]
+1 @charleseb @awheeler-mmi

**Comment by PizzaG** [comment]
+1

**Comment by klabit87** [comment]
@mbissaromoto

**Comment by chenyt9** [comment]
@all，
Pls refer to:https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPB29.73-81.txt
Thanks.
