### ISSUE TITLE
[QUESTION]: Android 11 vendor_boot devices

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/readme#36]
Hello, I'm looking for instructions on how to add the modules to the vendor_boot partition as happens in hanoip and other devices. Please provide instructions about this partition and what is its access mode on your devices.

Provide instructions for hanoip

**HANOIP_RETAIL_11_RRIS31.Q1-42-42-3-2**

**Comment by chenyt9** [comment]
@kytoaq , here is the kernel build instructions for hanoip 
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-RRIS31.Q1-42-51-12-4
