### ISSUE TITLE
[REQUEST] Edge 20 pro

### ISSUE THREAD

**Issue by error0x001** [MotorolaMobilityLLC/readme#37]
Hello there!

Could you share a manual how-to build [this](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/369) kernel for Motorola Edge 20 pro?

**Comment by chenyt9** [comment]
@error0x001 ，
Sorry for miss this msg.
Pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-RRA31.Q3-19-19.txt
Thanks
