### ISSUE TITLE
[REQUEST]Edge 30

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/readme#38]
Heyyo, I have a Motorola Edge 30 and I plan on maintaining TWRP and LineageOS for it, but I'm having problems compiling the kernel.

Can I please get build instructions for Dubai?

Thank you,
Marc "ThEMarD" Bourgoin

**Comment by chenyt9** [comment]
Pls refer to：https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S1RD32.55-33.txt
Thanks

**Comment by ThEMarD** [comment]
Wow that was fast! Thank you I'll take a look! :)
