### ISSUE TITLE
[REQUEST]Moto G71 5G [corfur] [MMI-S2RUB32.51-15-3]

### ISSUE THREAD

**Issue by Venkat3620** [MotorolaMobilityLLC/readme#39]
Please add build instructions for corfur, having trouble building touchscreen modules.
-tag RRUBS31.Q3-71-102-2-3

**Comment by chenyt9** [comment]
@Venkat3620 
Pls refer to: https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S2RUB32.51-15-3
