### ISSUE TITLE
[REQUEST] Moto G30

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/readme#40]
Heyyo, I want to work on the Motorola Moto G30 and I plan on building TWRP for it, but I'm having problems compiling the kernel.

Can I please get build instructions for caprip?

Thank you,
Marc "ThEMarD" Bourgoin

**Comment by chenyt9** [comment]
@ThEMarD pls refer to:https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-RRCS31.Q1-3-56-2
