### ISSUE TITLE
[REQUEST] Build instructions for XT2213-3 MMI-S1SA32.47-77

### ISSUE THREAD

**Issue by damnthefall** [MotorolaMobilityLLC/readme#41]
Trying to develop for the XT2213-3 Austin unfortunately there isn't much info available for building for mediatek devices. Please release a readme for this device if possible!

**Comment by chenyt9** [comment]
@damnthefall ,Pls refer to:https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S1SA32.47-77
