### ISSUE TITLE
[REQUEST]Motorola G82

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/readme#42]
Heyyo, I have a friend with the Motorola G82 and I plan on helping them build TWRP and LineageOS for it, but I'm having problems compiling the kernel.

Can I please get build instructions for rhodep?

Thank you,
Marc "ThEMarD" Bourgoin

**Comment by chenyt9** [comment]
@ThEMarD ,Pls refer to:https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S1SU32.73-41-2-4
