### ISSUE TITLE
[REQUEST] Build instructions for Edge 30 Ultra (XT2241-2) - S3SQ32.16-16-28

### ISSUE THREAD

**Issue by gabriel-hurtado** [MotorolaMobilityLLC/readme#43]
I am trying to build the kernel, but I am honestly a bit lost. Instructions or a prebuilt kernel would be amazing

**Comment by chenyt9** [comment]
@gabriel-hurtado ,Pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S3SQ32.16-16-28
