### ISSUE TITLE
[REQUEST] Build instructions for XT2225-2(rhodep-cn)

### ISSUE THREAD

**Issue by HorseLuke** [MotorolaMobilityLLC/readme#45]
Hello, could you please release build instructions for XT2225-2(rhodep-cn) S1SU32.73-34-7 and S1SU32.73-112-22? Thanks!

PS: I found kernel source S1SU32.73-34-7(https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SU32.73-34-7 ), but could not found kernel source S1SU32.73-112-22.

**Comment by HorseLuke** [comment]
OK, I found a solution.

For those who are interested, just follow build instructions for "The Generic Kernel Image (GKI) project". XT2225-2(rhodep-cn) is compatible with "common-android11-5.4" branch.

Links: https://source.android.com/docs/setup/build/building-kernels

**Comment by chenyt9** [comment]
@HorseLuke ,pls refer to :https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S1SU32.73-34-7.txt

**Comment by HorseLuke** [comment]
@chenyt9 thanks!
