### ISSUE TITLE
[REQUEST] Build instructions for motorola edge 30 fusion (tundra)

### ISSUE THREAD

**Issue by schqiushui** [MotorolaMobilityLLC/readme#47]
Please update building instructions for tundra, It‘s hard to build a kernel whitout extra kernel moduls config for this device. 
Thank you!

**Comment by chenyt9** [comment]
@schqiushui ,Pls refer to;https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S3SJ32.1-86-1.txt

**Comment by schqiushui** [comment]
Thank you very much for your updated document, but I found a problem that the kernel modules configurations are missing in that file. Compared with xpeng, another msm-5.4 kernel‘s building instruction, there are no configurations of WLAN drivers and other kernel modules. So, am I missing something? 
please help me. 
Thanks again.

**Comment by chenyt9** [comment]
@schqiushui ， Aleady update the readme file. Pls see the file for detail. Thanks.
