### ISSUE TITLE
[REQUEST] Motorola Edge (2022)

### ISSUE THREAD

**Issue by mfossen** [MotorolaMobilityLLC/readme#56]
Hello can we get build instructions for Motorola Edge (2022) codenamed tesla?

Build number: S2STS32.71-118-4-2

Thanks in advance!

**Comment by chenyt9** [comment]
@mfossen ,
you can refer to: 
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S2ST32.71-89
Thanks

**Comment by mfossen** [comment]
Thank you @chenyt9, I appreciate it!
