### ISSUE TITLE
Request for kernel build instructions for Moto G Power 5G (devonn, T1TOS33.33-45-23-1)

### ISSUE THREAD

**Issue by dynamikmechanik** [MotorolaMobilityLLC/readme#61]
Hi, I am a developer who is interested in working on the Moto G Power 5G. I would like to request the kernel build instructions for the device with the following specifications:

- Model: Moto G Power 5G
- Build Number: T1TOS33.33-45-23-1
- Codename: devonn

Thank you for your time.

**Comment by dynamikmechanik** [comment]
Please help @asbraga-motorola @chenyt9 @LONGCHEER-01 sorry to call you out

**Comment by chenyt9** [comment]
@dynamikmechanik , pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-T1TOS33.33-45-23-1
