### ISSUE TITLE
Request for kernel build instructions for Moto G Play (maui, S3SG32.39-191)

### ISSUE THREAD

**Issue by dynamikmechanik** [MotorolaMobilityLLC/readme#62]
Hi, I am a developer who is interested in working on the Moto G Play. I would like to request the kernel build instructions for the device with the following specifications:

    Model: Moto G Play
    Build Number: S3SG32.39-191
    Codename: maui

Thank you for your time.

**Comment by chenyt9** [comment]
@dynamikmechanik ,pls refer to:https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-S3SG32.39-191R2
