### ISSUE TITLE
[Request] build guide for moto edge 40 neo

### ISSUE THREAD

**Issue by sr0077** [MotorolaMobilityLLC/readme#67]
Please release build guide for edge 40 neo
Build no: T3TM33.23-141-2
Thanks

**Comment by chenyt9** [comment]
@sr0077 ， 
pls refer to https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-T3TM33.23-141-2

**Comment by sr0077** [comment]
@chenyt9 
Which files needs to download from gki
and where to put it ? https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-T3TM33.23-141-2#L33
