### ISSUE TITLE
Moto g 2014 MBM files

### ISSUE THREAD

**Issue by Thecrazyskull** [MotorolaMobilityLLC/readme#8]
This is probably not the best place to ask, but is motorola (if yes, when?) planning to release the MBM files compatible with the bootloader shipped in the 6.0 soak test?
The MBM files which are currently available online are 4.4.4 ones and are not compatible with the current bootloader, thus the people who are stuck in qhsusb dload mode due to accidently downgrading their bootloader because being simply unaware of the fact that the soak test updates the bootloader (or just blind me) are unable to get out of it.
I hope motorola would release these files.
Thanks.

**Comment by Thecrazyskull** [comment]
@tags07 @ccfries

**Comment by Thecrazyskull** [comment]
I reply would be nice you know... @tags07 @ccfries

**Comment by ccfries** [comment]
What mechanism did you use to do the downgrade to 4.4.4?  Fastboot will
block going backwards to an older bootloader when the security version is
updated (without bricking the phone).  Is this TWRP or some other custom
recovery?

**Comment by Thecrazyskull** [comment]
I installed the xt1069 factory image (was neccesary for the soak test), then i installed the 6.0 soak test over it.
I had some issues with my modem on the 6.0 soak test so i reverted back to the latest xt1068 factory image (the one with the stagefright fixes) via fastboot.
So i did it via fastboot, not with any custom recovery.

**Comment by tags07** [comment]
Do you have a secure device or a DE/Pure Android device?

**Comment by Thecrazyskull** [comment]
@tags07 a regular secure device.

**Comment by Thecrazyskull** [comment]
@tags07 @ccfries any update on this?

**Comment by Thecrazyskull** [comment]
Just sent my device for repair, hope they will accept it :)
